/** Nuxt file-based default path → public URL path */
export const PAGE_ROUTE_OVERRIDES = [
  { from: '/tts/ai-character-voice-generator', to: '/ai-character-voice-generator' },
  { from: '/tts/ai-girl-voice', to: '/ai-girl-voice' }, 
  { from: '/tts/ai-voice-girl', to: '/ai-voice-girl' },
  { from: '/tts/amans-voice', to: '/amans-voice' },
  { from: '/tts/audio-male', to: '/audio-male' },
  { from: '/tts/british-accent-generator', to: '/british-accent-generator' },
  { from: '/tts/british-voice', to: '/british-voice' },
  { from: '/tts/cantonese-text-to-speech', to: '/cantonese-text-to-speech' },
  { from: '/tts/deep-voice', to: '/deep-voice' },
  { from: '/tts/fake-voice', to: '/fake-voice' },
  { from: '/tts/female-ai-voice', to: '/female-ai-voice' },
  { from: '/tts/female-voice-generator', to: '/female-voice-generator' },
  { from: '/tts/female-voice-over', to: '/female-voice-over' },
  { from: '/tts/female-voice', to: '/female-voice' },
  { from: '/tts/free-text-to-speech-ai', to: '/free-text-to-speech-ai' },
  { from: '/tts/funny-tts-messages', to: '/funny-tts-messages' },
  { from: '/tts/funny-tts', to: '/funny-tts' },
  { from: '/tts/girl-ai-voice', to: '/girl-ai-voice' },
  { from: '/tts/girl-voice', to: '/girl-voice' },
  { from: '/tts/gossip-girl-voice', to: '/gossip-girl-voice' },
  { from: '/tts/guy-voice', to: '/guy-voice' },
  { from: '/tts/hot-girl-voice-generator', to: '/hot-girl-voice-generator' },
  { from: '/tts/kokoro-tts', to: '/kokoro-tts' },
  { from: '/tts/ladies-voice-converter', to: '/ladies-voice-converter' },
  { from: '/tts/male-audio', to: '/male-audio' },
  { from: '/tts/male-voice', to: '/male-voice' },
  { from: '/tts/male-voices', to: '/male-voices' },
  { from: '/tts/man-audio', to: '/man-audio' },
  { from: '/tts/man-text-to-speech', to: '/man-text-to-speech' },
  { from: '/tts/man-voice-over', to: '/man-voice-over' },
  { from: '/tts/man-voice', to: '/man-voice' },
  { from: '/tts/man-voices', to: '/man-voices' },
  { from: '/tts/mans-voice', to: '/mans-voice' },
  { from: '/tts/men-voice', to: '/men-voice' },
  { from: '/tts/natural-reader-tts', to: '/natural-reader-tts' },
  { from: '/tts/natural-reader', to: '/natural-reader' },
  { from: '/tts/natural-readers', to: '/natural-readers' },
  { from: '/tts/naturalreader', to: '/naturalreader' },
  { from: '/tts/naturalreaders', to: '/naturalreaders' },
  { from: '/tts/read-text', to: '/read-text' },
  { from: '/tts/text-reader', to: '/text-reader' },
  { from: '/tts/text-to-speech-reader', to: '/text-to-speech-reader' },
  { from: '/tts/text-to-speech', to: '/text-to-speech' },
  { from: '/tts/text-to-voice-female', to: '/text-to-voice-female' },
  { from: '/tts/the-mans-voice', to: '/the-mans-voice' },
  { from: '/tts/tts-mean', to: '/tts-mean' },
  { from: '/tts/tts-meaning', to: '/tts-meaning' },
  { from: '/tts/tts-reader', to: '/tts-reader' },
  { from: '/tts/ttsreader', to: '/ttsreader' },
  { from: '/tts/voice-deep', to: '/voice-deep' },
  { from: '/tts/voice-male', to: '/voice-male' },
  { from: '/tts/voice-man', to: '/voice-man' },
  { from: '/tts/voice-of-male', to: '/voice-of-male' },
  { from: '/tts/voice-of-man', to: '/voice-of-man' },
  { from: '/tts/voiceover-voice-over', to: '/voiceover-voice-over' },
  { from: '/vocal/ai-splitter', to: '/ai-splitter' },
  { from: '/vocal/ai-stem-splitter', to: '/ai-stem-splitter' },
  { from: '/vocal/instrumental-remover', to: '/instrumental-remover' },
  { from: '/vocal/isolate-vocals', to: '/isolate-vocals' },
  { from: '/vocal/music-remover', to: '/music-remover' },
  { from: '/vocal/remove-instrument', to: '/remove-instrument' },
  { from: '/vocal/separate-vocals', to: '/separate-vocals' },
  { from: '/vocal/splitter-ai', to: '/splitter-ai' },
  { from: '/vocal/vocal-extractor', to: '/vocal-extractor' },
  { from: '/vocal/vocal-separator', to: '/vocal-separator' },
  { from: '/vocal/vocal-splitter', to: '/vocal-splitter' },
  { from: '/vocal/voice-isolation', to: '/voice-isolation' },
  { from: '/vocal/voice-isolator', to: '/voice-isolator' },
] as const

export function applyPageRouteOverrides(pages: { path?: string }[]) {
  for (const page of pages) {
    const override = PAGE_ROUTE_OVERRIDES.find((o) => page.path === o.from)
    if (override) {
      page.path = override.to
    }
  }
}
