<template>
  <div class="friends-page max-w-7xl mx-auto px-4 py-8">
    <h1 class="text-2xl font-bold mb-8">{{ $t('friends.title') }}</h1>
    
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-for="link in friendLinks" :key="link.url" 
           class="friend-card p-4 border rounded-lg hover:shadow-lg transition-shadow">
        <a :href="link.url" target="_blank" rel="noopener noreferrer" class="block">
          <h2 class="text-lg font-semibold">{{ link.title }}</h2>
        </a>
      </div>
    </div>
  </div>
</template>

<script setup>
const friendLinks = ref([
  { title: 'tiktok text to speech', url: 'https://tiktokvoice.net' },
  { title: 'about me', url: 'https://about.me/zackreed' },
  { title: 'alles-ki', url: 'https://alles-ki.com/en/tool/AI%20Cover_cmagzq1kg002s12f42aafavu2' },
  { title: 'castle', url: 'https://castle.xyz/@zackreed' },
  { title: 'flickr', url: 'https://www.flickr.com/photos/203250283@N03/54688590943/in/dateposted-public/' },
  { title: 'heylink', url: 'https://heylink.me/aivoicelab.official/' },
  { title: 'huntscreens', url: 'https://huntscreens.com/en/products/ai-cover-4bc' },
  { title: 'kessel media', url: 'https://tiktok-voice.kessel.media/posts/pst_81533aa568414b2ab8d788008666f2b2/11-meilleurs-generateurs-de-voix-ia-2024' },
  { title: 'producthubx', url: 'https://producthubx.com/pt/product/aivoicelab/141217' },
  { title: 'seewhatnewai', url: 'https://www.seewhatnewai.com/ai-voice-lab' },
  { title: 'solo', url: 'https://solo.to/zackreed' },
  { title: 'urlscan', url: 'https://urlscan.io/result/019c93f4-3094-750b-ab23-45edf0c321fe/' },
  { title: 'vocus', url: 'https://vocus.cc/article/6724bf8efd897800019088da' },
  { title: 'webwiki', url: 'https://www.webwiki.com/aivoicelab.net' },
  { title: 'zproxy', url: 'https://aivoicelab-net.zproxy.org' },
  { title: 'sitelike', url: 'https://www.sitelike.org/similar/aivoicelab.net/' },
  { title: 'xinquji', url: 'https://xinquji.com/r/cd89285d08a687' },
  { title: 'gridinsoft', url: 'https://gridinsoft.ua/online-virus-scanner/url/aivoicelab-net' },
  { title: 'huggingface', url: 'https://huggingface.co/EricSmith' },
  { title: 'pinterest.com', url: 'https://www.pinterest.com/aivoicelabofficial/' },
  { title: 'zhihu', url: 'https://link.zhihu.com/?target=https%3A%2F%2Faivoicelab.net' },
  { title: 'storeboard', url: 'https://www.storeboard.com/aivoicelab' },
  { title: 'toolboxai', url: 'https://toolboxai.modeltheme.com/aivoicelab/' },
  { title: 'indiehackerstacks', url: 'https://indiehackerstacks.com/products/aivoicelab' },
  { title: 'toolai', url: 'https://www.toolai.io/ko/ai/ai-cover-generator' },
  { title: 'raindrop', url: 'https://raindrop.io/aivoicelab-official/audio-58522063' },
  { title: 'privacypolicies.com', url: 'https://www.privacypolicies.com/live/142ee052-d31a-43fa-a754-acb9aebd0720' },
  { title: 'peerlist', url: 'https://peerlist.io/ericaivoice' },
  { title: 'tinylaunch', url: 'https://www.tinylaunch.com/launch/5135' },
  { title: 'promptzone', url: 'https://www.promptzone.com/eric_eca7f013c43b1b30d964/the-five-best-ai-cover-tools-in-2025-i34' },
  { title: 'appmiu', url: 'https://www.appmiu.com/go/jrub' },
  { title: 'accio', url: 'https://www.accio.com/share/b488931ceaf94dafbe92984ecd248c37?language=zh_CN&langRedirect=1' },
  { title: 'freelistingusa', url: 'https://www.freelistingusa.com/listings/aivoicelab' },
  { title: 'recordsetter', url: 'https://recordsetter.com/user/ZackReed' },
  { title: 'imooc', url: 'https://www.imooc.com/article/365150' },
  { title: 'viesearch', url: 'https://viesearch.com/24p9q/feature' },
  { title: 'ababtools', url: 'https://ababtools.com/?post=5461' },
  { title: 'crxsoso', url: 'https://crxsoso.com/webstore/detail/glkhcffpnmknmaajjaeimfaoaekokdnl' },
  { title: "livedoor", url: "https://benjamin1990.livedoor.blog/archives/5075358.html" },
  { title: "alternativeto", url: "https://alternativeto.net/software/ai-voice-lab/about/" },
  { title: 'stackexchange', url: "https://ai.stackexchange.com/users/90711/benjamin-carter" },
  { title: 'bio', url: 'https://bio.site/aivoicelab' },
  { title: 'Cal', url: 'https://cal.com/zack-reed-zwglk9' },
  { title: "devhunt", url:"https://devhunt.org/@ZackReed_391" },
  { title: 'producthunt', url: 'https://www.producthunt.com/products/aivoicelab-2?launch=aivoicelab-2' },
  { title: 'beehiiv', url: 'https://zacksreed.beehiiv.com/' },
  { title: 'chatgpt', url: 'https://chatgpt.com/share/6886fd80-120c-800e-aa46-ee0298a62e32' },
  { title: 'rewards bing', url: 'https://rewards.bing.com/search?q=aivoicelab&qs=ds&FPIG=51E78ED0C7E34FB6B3BF29F8AFA27829&first=1&FORM=PERE' },
  { title: 'yahoo', url: 'https://ro.search.yahoo.com/mobile/s;_ylt=Awr90l6XnKFoy8sbdwIbigx.;_ylu=Y29sbwNncTEEcG9zAzEEdnRpZAMEc2VjA3BhZ2luYXRpb24-?p=aivoicelab&ei=UTF-8&b=1&pz=7&xargs=0' },
  { title: 'AiToolGo', url: 'https://www.aitoolgo.com' },
  { title: 'notion.so', url: 'https://www.notion.so/The-Five-Best-AI-Cover-Tools-in-2025-253689dffd7280ef8674e105f7645d84' },
  { title: 'tumblr', url: 'https://www.tumblr.com/dmcl/792210067048054784/the-five-best-ai-cover-tools-in-2025?source=share' },
  { title: 'bitly', url: 'https://bit.ly/472cRuW' },
  { title: 'izzi', url: 'https://aigc.izzi.cn/sites/24998.html' },
  { title: 'hashnode', url: 'https://zack-reeds-blog.hashnode.dev/the-five-best-ai-cover-tools-in-2025' },
  { title: 'forem', url: 'https://forem.com/eric_eca7f013c43b1b30d964/the-five-best-ai-cover-tools-in-2025-3o4b' },
  { title: 'provenexpert', url: 'https://www.provenexpert.com/zackreed/' },
  { title: "github overseas", url: "https://github.com/gowtdy/Noteworthy-Overseas-Websites" },
  { title: "tinylaun", url: "https://www.tinylaun.ch/launch/5135" },
  { title: "saashub", url: "https://www.saashub.com/ai-voice-lab" },
  { title: "indiepa", url: "https://indiepa.ge/zackreed" },
  { title: "emailsherlock", url: "https://www.emailsherlock.com/hosts/aivoicelab.net/" },
  { title: "microlaunch", url: "https://microlaunch.net/p/aivoicelab-b9a3c2" },
  { title: "ithy", url: "https://ithy.com/article/how-to-use-aivoicelab-7rniph45" },
  { title: "solo.xin", url: "https://solo.xin/topic/2566" },
  { title: 'blogspot', url: 'https://aivoicelab.blogspot.com/2025/08/five-best-ai-cover-tools-in-2025.html' },
  { title: 'behance', url: 'https://www.behance.net/zackreed5' },
  { title: 'vimeo', url: 'https://vimeo.com/1105711430?share=copy' },
  { title: 'wordpress', url: 'https://aivoicelab4.wordpress.com/' },
  { title: 'aibucket', url: 'https://www.aibucket.io/tools/ai-voice-lab'},
  { title: 'logosc', url: 'https://hao.logosc.cn/p/4958' },
  { title: 'tgso', url: 'https://tgso.top/search/aivoicelab' },
  { title: 'chomeaddon', url: 'https://sem.3ue.com/search/2025%E5%8A%B1%E5%BF%97%E9%B8%A1%E6%B1%A4?__gmitm=ayWzA3*l4EVITnKJu4tFUM*NR1lbeGNdLX13g1E~l8O0' },
  { title: 'awesometechstack', url: 'https://awesometechstack.com/analysis/website/aivoicelab.net?protocol=https:' },
  { title: 'genspark', url: 'https://www.genspark.ai/agents?id=483a2b78-11be-489b-bc6e-1029d8b49891' },
  { title: 'paragraph', url: 'https://paragraph.com/@zackreed/preview/R8bqXiurJdXaX57UcPP7' },
  { title: 'start', url: 'https://start.me/w/BG694w' },
  { title: "wechalet", url: "https://wechalet.cn/appstore/detail/4pm5" },
  { title: "spotsaas.com", url: "https://www.spotsaas.com/product/voicelab" },
  { title: "All The Best AI Tools", url: "https://allinai.tools" }, 
  { title: "Ai Tools List", url: "https://aiai.tools/" },
  { title: "steemit", url: "https://steemit.com/ai/@benjamin2047/from-crypto-trader-to-ai-voice-wizard-my-journey-as-an-indie-dev" },
  { title: 'vsw', url: 'http://domain.vsw.jp/aivoicelab.net/' },
  { title: 'patreon', url: 'https://www.patreon.com/posts/how-to-use-133513854?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link' },
  { title: 'listly', url: 'https://list.ly/list/CdIM-ai-voice' },
  { title: 'openi', url: 'https://openi.cn/sites/284644.html' },
  { title: 'owwly', url: 'https://owwly.com/products/others' },
  { title: 'altern', url: 'https://altern.ai/category/music_and_voice' },
  { title: 'lb1581', url: 'https://www.lb1581.xyz/post/12588.html' },
  { title: '1ai', url: 'https://www.1ai.net/en/35074.html' },
  { title: 'bestofai', url: 'https://bestofai.com/tool/aivoicelab'},
  { title: 'Free AI Tools', url: 'https://www.scriptbyai.com' },
  { title: 'comic studio', url: 'https://comic.studio/u/zackreed' },
  { title: 'zackreed', url: 'https://qooh.me/zackreed' },
  { title: 'felo.ai', url: 'https://felo.ai/search/7NUwAjrL9UJ8CpgrLkx6xt' },
  { title: 'vercel', url: 'https://webcatalog-two.vercel.app/en/apps/ai-voice-lab' },
  { title: 'fazier', url: 'https://fazier.com/p/zack-reed' },
  { title: 'wykop', url: 'https://wykop.pl/ludzie/zack-reed' },
  { title: 'toolsfine', url: 'https://toolsfine.com/' },
  { title: 'toolpilot', url: 'https://www.toolpilot.ai' },
  { title: 'SeekAIs - AI Tools Directory', url: 'https://SeekAIs.com/' },
  { title: 'xiuxiu', url: 'https://www.xiuxiu.com/middlepage/3293/' },
  { title: 'yejiuqiu', url: 'http://wendang.yejiuqiu.cn/docs/post-63/page-944' },
  { title: 'ramen', url: 'https://ramen.tools/@ZackReed' },
  { title: 'startupfa', url: 'https://startupfa.me/s/ai-cover' },
  { title: 'uneed', url: 'https://www.uneed.best/profile/zack-reed' },
  { title: 'lovable', url: 'https://launched.lovable.dev/aivoicelab' },
  { title: 'logicballs', url: 'https://logicballs.com/ai-tools/aivoicelab' },
  { title: 'perplexity', url: 'https://www.perplexity.ai/search/why-aivoicelab-net-is-the-best-SBRYbLM6QJmZKg28loF9Xw' },
  { title: 'mmwatches', url: 'https://mmwatches.co.uk/2d4d491512674b3c4b2d6e9c087e2d2c-listing' },
  { title: 'Adobe Community', url: 'https://community.adobe.com/t5/user/viewprofilepage/user-id/43425417' },
  { title: "xploredomains", url: "https://www.xploredomains.com/2024-09-22?page=158" },
  { title: "imyshare", url: "https://imyshare.com/chat/#share" },
  { title: "thataicollection", url: "https://thataicollection.com/submit/review-and-submit/" },
  { title: "tanronggui", url:"https://tanronggui.xyz/member/azhao" },
])
</script>